name: Publish to mainnet

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_MAINNET }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_MAINNET }}
  AWS_DEFAULT_REGION: eu-central-1
  AWS_DISTRIBUTION_ID: ${{ secrets.AWS_DISTRIBUTION_ID_MAINNET }}
  AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME_MAINNET }}
  VITE_BACKEND_URL: https://backend-v115.mainnet.alephium.org
  VITE_NETWORK_TYPE: mainnet
  VITE_NODE_URL: https://node-v20.mainnet.alephium.org

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Build frontend
        run: npm ci && npm run build && node docker/init-server-data.js

      - name: Sync files to S3
        run: aws s3 sync ./build/ s3://$AWS_BUCKET_NAME --acl public-read --delete --cache-control max-age=604800

      - name: Notify CloudFront about the changes
        run: aws cloudfront create-invalidation --distribution-id ${AWS_DISTRIBUTION_ID} --paths "/*"

      - name: Deploy mainnet via webhook
        uses: distributhor/workflow-webhook@v3
        env:
          webhook_url: ${{ secrets.MAINNET_WEBHOOK_URL }}
          webhook_secret: ${{ secrets.MAINNET_WEBHOOK_SECRET }}
